#!/usr/bin/python3
import sys

def factorize():
    try:
        if len(sys.argv) != 2:
            print("Usage: factors <file>")
            return

        input_file = sys.argv[1]
        with open(input_file) as file:
            for line in file:
                number = int(line)
                factors = find_factors(number)
                print(f"{number} = {factors[0]} * {factors[1]}")

    except (IndexError, FileNotFoundError):
        print("Usage: factors <file>")
    except (ValueError, ZeroDivisionError):
        print("Invalid input in the file.")

def find_factors(number):
    for i in range(2, number // 2 + 1):
        if number % i == 0:
            return (i, number // i)
    return (number, 1)

if __name__ == "__main__":
    factorize()

