#!/usr/bin/python3

import sys

def factorize_number():
    """
    This function reads a file and factors numbers in the format n = p * q.
    It prints the factors of the given numbers.
    """
    try:
        input_file = sys.argv[1]
        with open(input_file) as file:
            for line in file:
                number = int(line)
                if number % 2 == 0:
                    print("{} = {} * {}".format(number, number // 2, 2))
                    continue
                divisor = 3
                while divisor < number // 2:
                    if number % divisor == 0:
                        print("{} = {} * {}".format(number, number // divisor,
                        divisor))
                        break
                    divisor += 2
                if divisor == (number // 2) + 1:
                    print("{} = {} * {}".format(number, number, 1))
    except (IndexError, FileNotFoundError):
        pass

factorize_number()

