#!/usr/bin/python3
import sys

# Function to factorize numbers
def factorize():
    """
    This function reads a file and converts numbers into the format n = p * q.
    """
    try:
        input_file = sys.argv[1]
        with open(input_file) as file:
            for number in file:
                number = int(number)
                if number % 2 == 0:
                    print("{} = {} * {}".format(number, number // 2, 2))
                    continue
                divisor = 3
                while divisor < number // 2:
                    if number % divisor == 0:
                        print("{} = {} * {}".format(number, number // divisor, divisor))
                        break
                    divisor += 2
                if divisor == (number // 2) + 1:
                    print("{} = {} * {}".format(number, number, 1))
    except (IndexError):
        pass

# Auto-start the factorization
factorize()

